### PR TITLE
 Create Programming language and service icons

### PR DESCRIPTION
**Pull request by vlgunarathne**
These programming icons are used for the SDK generation feature of the API Manager.

The following 50 icons are included in this PR.
"angular"
"babel"
"backbone"
"bitbucket"
"c"
"cakephp"
"ceylon"
"chrome"
"coffeescript"
"confluence"
"couchdb"
"cplusplus"
"csharp"
"css3"
"django"
"docker"
"dotnet"
"firefox"
"git"
"go"
"heroku"
"html5"
"intellij"
"ionic"
"javascript"
"jetbrains"
"meteor"
"mongodb"
"mysql"
"nginx"
"nodewebkit"
"oracle"
"phpstorm"
"postgresql"
"pycharm"
"python"
"rails"
"react"
"redhat"
"ruby"
"safari"
"swift"
"tomcat"
"typescript"
"vagrant"
"vim"
"webpack"
"webstorm"
"wordpress"
"yarn"

### CODE REVIEW

**Comment by dakshika** [comment]
Is there any requirement of adding these icons to wso2 font?

**Comment by vlgunarathne** [comment]
This PR is to address the following issue.
https://github.com/wso2-dev-ux/font-wso2/issues/102

**Comment by thusithak** [comment]
@vlgunarathne could you go through [ CONTRIBUTING.md ](https://github.com/wso2-dev-ux/font-wso2/blob/master/CONTRIBUTING.md) 's detailed explanation on SVG icon's anatomy when making above changes. 

Don't hesitate to ask @srsharon and @jeradrutnam if you have any difficulty moving on.

**Comment by dakshika** [comment]
PR hasn't updated according to the reviews and feedback

**Pull request closed without merging**
